name: async_notify
description: Notify wait/notify library.
version: 0.0.2
homepage: https://github.com/vivitainc/flutter_async_notify

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
